export const FEATURE_FLAG_MODEL_NAME = 'FeatureFlag';
export const SETTING_MODEL_NAME = 'Setting';
export const BANNER_MODEL_NAME = 'Banner';
export const AUDIT_LOG_MODEL_NAME = 'AuditLog';

export const AUDIT_ACTIONS = {
  USER_BLOCKED: 'USER_BLOCKED',
  USER_UNBLOCKED: 'USER_UNBLOCKED',
  PROVIDER_KYC_APPROVED: 'PROVIDER_KYC_APPROVED',
  PROVIDER_KYC_REJECTED: 'PROVIDER_KYC_REJECTED',
  BOOKING_REFUNDED: 'BOOKING_REFUNDED',
  ORDER_STATUS_CHANGED: 'ORDER_STATUS_CHANGED',
  WALLET_ADJUSTED: 'WALLET_ADJUSTED',
  REPORT_RESOLVED: 'REPORT_RESOLVED',
  SETTING_UPDATED: 'SETTING_UPDATED',
  FEATURE_FLAG_UPDATED: 'FEATURE_FLAG_UPDATED',
} as const;

export type AuditAction = (typeof AUDIT_ACTIONS)[keyof typeof AUDIT_ACTIONS];
