export const PROVIDER_MODEL_NAME = 'Provider';

export const KYC_STATUSES = {
  PENDING: 'PENDING',
  APPROVED: 'APPROVED',
  REJECTED: 'REJECTED',
} as const;

export type KycStatus = (typeof KYC_STATUSES)[keyof typeof KYC_STATUSES];

export const KYC_DOCUMENT_TYPES = {
  GOVERNMENT_ID: 'GOVERNMENT_ID',
  BUSINESS_LICENSE: 'BUSINESS_LICENSE',
  PROFESSIONAL_CERTIFICATE: 'PROFESSIONAL_CERTIFICATE',
  ADDRESS_PROOF: 'ADDRESS_PROOF',
  OTHER: 'OTHER',
} as const;

export type KycDocumentType = (typeof KYC_DOCUMENT_TYPES)[keyof typeof KYC_DOCUMENT_TYPES];
